export default {
  PlayerCharacter: {
    Chronicle: 'Breaking Barriers',
    Concept: '',
    Court: '',
    Kith: '',
    Mask: '',
    Mien: '',
    Name: 'Yuri',
    Player: 'Aaron',
    Seeming: '',
  },
  Attributes: {
    Composure: 2,
    Dexterity: 3,
    Intelligence: 1,
    Manipulation: 3,
    Presence: 1,
    Resolve: 3,
    Stamina: 3,
    Strength: 1,
    Wits: 2,
  },
  Skills: {
    Mental: {
      Academics: 0,
      Computer: 0,
      Crafts: 0,
      Investigation: 0,
      Medicine: 0,
      Occult: 0,
      Politics: 0,
      Science: 0,
    },

    Physical: {
      Athletics: 0,
      Brawl: 0,
      Drive: 0,
      Firearms: 0,
      Larceny: 0,
      Stealth: 0,
      Survival: 0,
      Weaponry: 0,

    },
    Social: {
      AnimalKen: 0,
      Empathy: 0,
      Expression: 0,
      Intimidation: 0,
      Persuasion: 0,
      Socialize: 0,
      Streetwise: 0,
      Subterfuge: 0,
    },
  },
  GoblinContracts: {},
  Clarity: 0,
  Contracts: {},
  Glamour: 0,
  Health: { current: 6, total: 7, },
  Merits: {},
  Willpower: { current: 6, total: 7, },
  Wyrd: 1,

};
